### ISSUE TITLE
TypeError: '_IncompatibleKeys' object is not callable

### ISSUE THREAD

**Issue by shaktibangare** [eio/satellite-pose-estimation#1]
When trying to run  python run_model.py -l -ts giving error-
Running with device: cuda
Start: 2023-12-08 12:55:58.568544
Loading the saved model: `results/model+optimizer.pth`
Traceback (most recent call last):
  File "/home/hil/dev/satellite-pose-estimation-main/run_model.py", line 209, in <module>
    model, optimizer = load_model()
  File "/home/hil/dev/satellite-pose-estimation-main/save_and_load.py", line 38, in load_model
    model = Model().to(DEVICE)
NameError: name 'Model' is not defined. Did you mean: 'model'?

but after resolving coming other error
Running with device: cuda
Start: 2023-12-08 17:01:08.636899
Loading the saved model: `results/model+optimizer.pth`
Model loaded.
Testing for images in: Stream-2/test_synthetic/images/

Start Testing for Epoch 1...
Traceback (most recent call last):
  File "/home/hil/dev/satellite-pose-estimation-main/run_model.py", line 224, in <module>
    test_losses = test_process(
  File "/home/hil/dev/satellite-pose-estimation-main/run_model.py", line 132, in test_process
    outputs = model(inputs)
TypeError: '_IncompatibleKeys' object is not callable

please check the code.

**Comment by eio** [comment]
Hello and thank you for your interest in this project.
Unfortunately we can not offer direct support as it is no longer under active development.
It appears the issues you're seeing are a result of the commit titled "refactor and cleanup" (a8fb68b).
Trying an earlier commit should hopefully resolve your issues.
All the best and happy coding.
